# Generated by Django 5.1.15 on 2026-07-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='asistio',
            field=models.BooleanField(blank=True, help_text='True si el paciente asistió, False si no, Null si aún no se sabe', null=True),
        ),
    ]
