# Generated by Django 5.1.15 on 2026-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_turno_asistio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20),
        ),
    ]
